# Generated by Django 2.1.4 on 2019-01-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekonomi', '0002_auto_20181213_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('kind', models.IntegerField(choices=[(0, 'ica_csv')], default=0, verbose_name='Kind')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
